main:
	bison -d 2005104.y
	flex 2005104.l
	g++ 2005104.tab.c lex.yy.c
	./a.out test3_i.c

loop:
	./sample.out input/loop.c

func:
	./sample.out input/func.c

exp:
	./sample.out input/exp.c

test1:
	./sample.out input/test1_i.c

test2:
	./sample.out input/test2_i.c

test3:
	./sample.out input/test3_i.c

test4:
	./sample.out input/test4_i.c

test5:
	./sample.out input/test5_i.c

test6:
	./sample.out input/test6_i.c

test7:
	./sample.out input/test7_i.c
test:
	./sample.out test.c

